# -*- coding: utf-8 -*-
"""python_basics_nagaraju_kasa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5wtoiMhmpdTdyAm15ES1Rcbm6C3U_Jq
"""

name = 'Nagaraju Kasa'
age = 35
height = 5.8
is_student = True

#Task1: name (string), age (integer), height in meters (float), and whether they are a student (boolean). Print all four values in a single print() statement.
print('# Task 1 #')
print("Name :", name, "Age :", age, "Height :", height, "Is Student :", is_student)

#Task2: String Formatting Using the variables from Task 1, print a sentence in the following format: Name: <name> | Age: <age> | Height: <height> | Student: <is_student>
print('# Task 2 #')
print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")

#Task 3: Arithmetic Operations Using the age variable, calculate and print:
# Age in months
# Age in days (assume 365 days/year)
# The remainder when age is divided by 7
# Age raised to the power of 2

age_in_months = age * 12
age_in_days = age * 365
age_remainder = age % 7
age_power_of_two = age ** 2

print('# Task 3 - Arithmetic Operations #')
print(f"Age in Months = {age_in_months}")
print(f"Age in Days = {age_in_days}")
print(f"The remainder when age is divided by 7 = {age_remainder}")
print(f"Age raised to the power of 2 = {age_power_of_two}")